{
 "title": "Ping Exporter - Inter node ping statistics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "src_ip",
    "label": "NodeIP",
    "query": {
     "query": "label_values(ping_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current ping RTT (source: $src_ip)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " ping_rtt_ms{instance=~\"$src_ip.*\",type=\"mean\",target!=\"$src_ip\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "PING loss  (source: $src_ip)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ping_loss_percent{instance=~\"$src_ip.*\",target!=\"$src_ip\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "PING RTT  [mean] (source: $src_ip)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_ms{instance=~\"$src_ip.*\",type=~\"mean\",target!=\"$src_ip\"}",
     "legendFormat": "ping_rtt_ms({{type}}) {{target}}"
    }
   ]
  },
  {
   "title": "PING RTT [best|worst] (source: $src_ip)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_ms{instance=~\"$src_ip.*\",type=~\"best|worst\",target!=\"$src_ip\"}",
     "legendFormat": "ping_rtt_ms({{type}}) {{target}}"
    }
   ]
  }
 ]
}